### ISSUE TITLE
vps install

### ISSUE THREAD

**Issue by Jordan-b1027** [PeWe79/AzuraCast-Player#4]
cant get it installed on my ipv6 vps can i get help

**Comment by PeWe79** [comment]
Hi, of course you can installed.

**Comment by burjuyz** [comment]
you can use docker

Dockerfile
```
# Используем официальный образ Node.js
FROM node:18-alpine

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь проект внутрь контейнера
COPY . .

# Собираем проект
RUN npm run build

# Открываем порт для работы live-server
EXPOSE 8080

# Устанавливаем live-server
RUN npm install -g live-server

# Запускаем сервер для разработки или продакшена
CMD ["npx", "live-server", "--host=0.0.0.0", "--port=8080", "--open=."]
```

docker-compose.yml

```
services:
  azuracast-player:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: ["npx", "live-server", "--host=0.0.0.0", "--port=8080", "--open=."]
```
